apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deplyoment
  labels:
    app: nginx 
spec:
  replicas: 3 #it will create three pod inside my deplyoment
  selector: 
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx  
    spec: 
      containers:
      - name: nginx  
        image: nginx:1.14.2
        ports:
        - containerPort: 80
    